<?php

$labels = array();
$labels['awaymessage'] = 'Away';
$labels['save'] = 'Save';
$labels['message'] = 'Message: ';
$labels['subject'] = 'Subject: ';
$labels['active'] = 'Activate: ';
$labels['title'] = 'Configure away message';

$messages['connecterror'] = 'Could not save away message. Connection error.';
$messages['internalerror'] = 'Could not save away message.';
$messages['enableerror'] = 'Could not save away message. Enabled away message must have subject and message.';
?>
