<?php
 
$labels = array();
$labels['awaymessage'] = 'Ausência';
$labels['save'] = 'Salvar';
$labels['message'] = 'Mensagem: ';
$labels['subject'] = 'Assunto: ';
$labels['active'] = 'Ativar: ';
$labels['title'] = 'Configuração da mensagem de ausência';

$messages['connecterror'] = 'Não foi possível gravar mensagem de ausência. Erro de conexão.';
$messages['internalerror'] = 'Não foi possível gravar mensagem de ausência.';
$messages['enableerror'] = 'Não foi possível gravar mensagem de ausência. Quando ativada, o título e a mensagem devem ser preenchidos.';
?>
